# Generated by Django 4.2.13 on 2024-05-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commander_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="Liscence_Plate",
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name="cars",
            name="Assigned_Job",
            field=models.IntegerField(default=None),
        ),
    ]
