# Generated by Django 4.2.13 on 2024-05-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commander_dashboard", "0002_jobs_liscence_plate_alter_cars_assigned_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="Assigned_Job",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="jobs",
            name="Liscence_Plate",
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
